package:
  name: k2
  version: "{{ environ.get('K2_BUILD_VERSION') }}"

source:
  path: "{{ environ.get('K2_ROOT_DIR') }}"

build:
  number: 0
  string: cu{{ environ.get('K2_CUDA_VERSION') }}+torch{{ environ.get('K2_TORCH_VERSION') }}+py{{py}}

requirements:
  host:
    - cmake
    - python
    - setuptools
    - pytorch={{ environ.get('K2_TORCH_VERSION') }}
    - cudatoolkit={{ environ.get('K2_CUDA_VERSION_STR') }}

about:
  home: https://github.com/k2-fsa/k2
  license: Apache V2
  license_file: LICENSE
  summary: FSA/FST algorithms, differentiable, with PyTorch compatibility
