package:
  name: k2
  version: "{{ environ.get('K2_BUILD_VERSION') }}"

source:
  path: "{{ environ.get('K2_ROOT_DIR') }}"

build:
  number: 0
  string: cu{{ environ.get('K2_CUDA_VERSION') }}+torch{{ environ.get('K2_TORCH_VERSION') }}+py{{py}}
  script_env:
    - K2_IS_GITHUB_ACTIONS
    - K2_CUDA_VERSION
    - K2_CUDA_VERSION_STR
    - K2_PYTHON_VERSION
    - K2_PYTHON_VERSION
    - K2_BUILD_TYPE

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake=3.18
    - python={{ environ.get('K2_PYTHON_VERSION') }}
    - pytorch={{ environ.get('K2_TORCH_VERSION') }}
    - cudatoolkit={{ environ.get('K2_CUDA_VERSION_STR') }}
    - gcc_linux-64=7
  run:
    - python={{ environ.get('K2_PYTHON_VERSION') }}
    - pytorch={{ environ.get('K2_TORCH_VERSION') }}
    - cudatoolkit={{ environ.get('K2_CUDA_VERSION_STR') }}
    - gcc_linux-64=7

about:
  home: https://github.com/k2-fsa/k2
  license: Apache V2
  license_file: LICENSE
  summary: FSA/FST algorithms, differentiable, with PyTorch compatibility
