# Copyright (c)  2020  Fangjun Kuang (csukuangfj@gmail.com)

# See ../../LICENSE for clarification regarding multiple authors

# refer to https://github.com/actions/starter-workflows/pull/47/files

name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
        gcc: [5]
        python-version: [3.6, 3.7, 3.8]

    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2

      - name: Install CUDA
        env:
          cuda: ${{ matrix.cuda }}
        run: |
          source ./scripts/github_actions/install_cuda.sh
          echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
          echo "${CUDA_HOME}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${CUDA_HOME}/lib:${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        shell: bash

      - name: Display NVCC version
        run: |
          which nvcc
          nvcc --version

      - name: Install GCC
        run: |
          sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
          echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
          echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV


      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install torch==1.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
          python3 -m pip install gdown # for downloading cudnn from gdrive
          python3 -m pip install wheel twine

      - name: Download cudnn 8.0
        run: |
          gdown --id 1-ULqFzK_HSMMYJz556LbddDVShXMoNwX --output cudnn-10.1-linux-x64-v8.0.2.39.tgz
          sudo tar xf cudnn-10.1-linux-x64-v8.0.2.39.tgz -C /usr/local

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        run: |
          pwd
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
          cat CMakeCache.txt

      - name: Build _k2
        shell: bash
        run: |
          cd build
          make _k2

      - name: Build pip packages
        shell: bash
        run: |
          sudo apt-get install chrpath
          ./scripts/build_pip.sh
          ls dist/
