# Copyright (c)  2020  Fangjun Kuang (csukuangfj@gmail.com)

# See ../../LICENSE for clarification regarding multiple authors

# refer to https://github.com/actions/starter-workflows/pull/47/files

name: build_conda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build_conda:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-16.04, ubuntu-18.04]
        os: [ubuntu-16.04]
        # python-version: [3.6, 3.7, 3.8, 3.9]
        python-version: [3.8]
        # from https://download.pytorch.org/whl/torch_stable.html
        # PyTorch 1.8.0 supports: cuda 10.1, 10.2 (default), 11.1
        # PyTorch 1.7.x supports: cuda 10.1, 10.2 (default), 11.0
        # PyTorch 1.6.0 supports: cuda 10.1, 10.2 (default)
        # PyTorch 1.5.x supports: cuda 10.1, 10.2 (default)
        # Other PyTorch versions are not tested
        # cuda: ["10.1", "10.2", "11.0", "11.1"]
        cuda: ["10.1"]
        # torch: ["1.5.0", "1.5.1", "1.6.0", "1.7.0", "1.7.1", "1.8.0"]
        torch: ["1.7.1"]
        # exclude:
        #   - cuda: "11.0" # exclude 11.0 for [1.5.0, 1.5.1, 1.6.0, 1.8.0]
        #     torch: "1.5.0"
        #   - cuda: "11.0"
        #     torch: "1.5.1"
        #   - cuda: "11.0"
        #     torch: "1.6.0"
        #   - cuda: "11.0"
        #     torch: "1.8.0"
        #   - cuda: "11.1" # exclude 11.1 for [1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1]
        #     torch: "1.5.0"
        #   - cuda: "11.1"
        #     torch: "1.5.1"
        #   - cuda: "11.1"
        #     torch: "1.6.0"
        #   - cuda: "11.1"
        #     torch: "1.7.0"
        #   - cuda: "11.1"
        #     torch: "1.7.1"
        #   - python-version: 3.9 # exclude Python 3.9 for [1.5.0, 1.5.1, 1.6.0, 1.7.0]
        #     torch: "1.5.0"
        #   - python-version: 3.9
        #     torch: "1.5.1"
        #   - python-version: 3.9
        #     torch: "1.6.0"
        #   - python-version: 3.9
        #     torch: "1.7.0"
    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies CUDA ${{ matrix.cuda }} PyTorch ${{ matrix.torch }}
        run: |
          which conda # print: /usr/bin/conda
          $CONDA/bin/conda info
          $CONDA/bin/conda install -y -c conda-forge cudatoolkit-dev=${{ matrix.cuda }}
          $CONDA/bin/conda install -y -c nvidia cudatoolkit=${{ matrix.cuda }} cudnn=8.0.4
          $CONDA/bin/conda install -y -c pytorch pytorch=${{ matrix.torch }} cudatoolkit=${{ matrix.cuda }}

      - name: Display NVCC version
        run: |
          nvcc --version

      - name: Display PyTorch version
        run: |
          python3 -m torch.utils.collect_env

      # - name: Build k2
      #   run: |
      #     BUILD_VERSION=$(python3 ./get_version.py)
      #     export BUILD_VERSION
      #     echo "BUILD_VERSION: $BUILD_VERSION"
      #
      #     $CONDA/bin/conda build --no-anaconda-upload -c pytorch ./scripts/conda/k2
