name: Ubunut - CPU wheels for huggingface

on:
  push:
    branches:
      - upload-hugging-face
    paths:
      - '.github/workflows/huggingface-cuda-ubuntu.yml'
      - 'scripts/github_actions/generate_build_matrix'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'k2/csrc/**'
      - 'k2/python/**'

concurrency:
  group: huggingface-ubuntu-cpu-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  generate_build_matrix:
    if: github.event_name == 'push'
    # see https://github.com/pytorch/pytorch/pull/50633
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python scripts/github_actions/generate_build_matrix.py
          # MATRIX=$(python scripts/github_actions/generate_build_matrix.py --test-only-latest-torch)
          MATRIX=$(python scripts/github_actions/generate_build_matrix.py)
          echo "::set-output name=matrix::${MATRIX}"

  huggingface_cpu_ubuntu:
    needs: generate_build_matrix
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Display date and time
        run: date

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install GCC 7
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y gcc-7 g++-7
          echo "CC=/usr/bin/gcc-7" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-7" >> $GITHUB_ENV

      - name: Display GCC version
        run: |
          gcc --version

      - name: Install PyTorch ${{ matrix.torch }}
        shell: bash
        run: |
          python3 -m pip install -qq --upgrade pip
          python3 -m pip install -qq wheel twine typing_extensions
          python3 -m pip install torch==${{ matrix.torch }}+cpu -f https://download.pytorch.org/whl/torch_stable.html
          python3 -m pip install --upgrade numpy

          python3 -c "import torch; print('torch version:', torch.__version__)"

      - name: Build pip packages
        shell: bash
        run: |
          export K2_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE -DK2_WITH_CUDA=OFF"
          export K2_MAKE_ARGS="-j2"
          python3 setup.py bdist_wheel
          ls -lh dist/

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-ubuntu-18.04
          path: dist/*.whl

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        # if: ${{ github.repository_owner == 'k2-fsa' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "csukuangfj@gmail.com"
          git config --global user.name "Fangjun Kuang"

          GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/k2 huggingface

          cp -v dist/*.whl huggingface/cpu/

          cd huggingface
          git pull
          git add cpu
          git commit -m "upload wheel by github actions"
          git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/k2 main
